window.STAGING_DEALS = [
  {
    "id": "catalog-412492",
    "sku": "412492",
    "title": "24H Matte Lipstick Astd",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/412492.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-400882",
    "sku": "400882",
    "title": "AD SC Wig Caps 3CT Astd",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/400882.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-846236",
    "sku": "846236",
    "title": "Adorn Small Hurricane",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/846236.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-379537",
    "sku": "379537",
    "title": "Baby Shark Baby Lotion 1oz",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/379537.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-379530",
    "sku": "379530",
    "title": "Baby Shark Baby Shampoo 1oz",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/379530.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-379533",
    "sku": "379533",
    "title": "Baby Shark Baby Shampoo Lvnd 1oz",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/379533.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-379535",
    "sku": "379535",
    "title": "Baby Shark Baby Wash 1oz",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/379535.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-367385",
    "sku": "367385",
    "title": "Bathroom Cleaner Kit",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/367385.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-318526",
    "sku": "318526",
    "title": "Blue 2-Tone 8\" Plate",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/318526.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-407263",
    "sku": "407263",
    "title": "Bowie Blue Striped Crew Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/407263.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-382620",
    "sku": "382620",
    "title": "BP Hot or Cold Face Mask",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/382620.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-402718",
    "sku": "402718",
    "title": "Bugs Bunny Gry Stripe Crew Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/402718.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-413552",
    "sku": "413552",
    "title": "Campbell's Spicy Tomato Soup 10.5oz",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/413552.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-392298",
    "sku": "392298",
    "title": "Care-Us Cooling Burn Pads 2CT",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/392298.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-333868",
    "sku": "333868",
    "title": "Carepak Astd Sheer Bandages 80CT",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/333868.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-333872",
    "sku": "333872",
    "title": "Carepak Clr Waterproof Bandages 25CT",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/333872.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-333862",
    "sku": "333862",
    "title": "Carepak Neon Color Bandages 30CT",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/333862.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-397740",
    "sku": "397740",
    "title": "Cheez-It Crew Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/397740.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-415203",
    "sku": "415203",
    "title": "Clearly Canadian Blackberry 8.8oz",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/415203.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-300724",
    "sku": "300724",
    "title": "CraftSq Alpha Stickers Color Astd",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/300724.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-327854",
    "sku": "327854",
    "title": "CraftSq Lrg Water Brush Pen 2CT",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/327854.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-361705",
    "sku": "361705",
    "title": "Crate w/ Holes White Mini Sq",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/361705.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-403094",
    "sku": "403094",
    "title": "E.T. Bicycle Crew Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/403094.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-390887",
    "sku": "390887",
    "title": "Elmo Black Crew Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/390887.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-402696",
    "sku": "402696",
    "title": "Elmo Crayons Red Crew Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/402696.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-402677",
    "sku": "402677",
    "title": "Elmo Crew Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/402677.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-405498",
    "sku": "405498",
    "title": "Freeze Dried Colorful Candy 1oz",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/405498.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-368075",
    "sku": "368075",
    "title": "Gain Sort Orig 9/60 CT B680",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/368075.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-402782",
    "sku": "402782",
    "title": "Gibson 7.75\" Rnd Dessert Plates",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/402782.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-252863",
    "sku": "252863",
    "title": "Grow Toys 2 PK",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/252863.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-404959",
    "sku": "404959",
    "title": "Hairitage Towel Scrunchie",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/404959.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-411542",
    "sku": "411542",
    "title": "Harmonica",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/411542.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-188749",
    "sku": "188749",
    "title": "Heart Shaped Beads 360PCS",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/188749.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-402263",
    "sku": "402263",
    "title": "Heinz Yellow Mustard Jumbo Eraser",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/402263.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-402647",
    "sku": "402647",
    "title": "Jello Is A Go Jumbo Eraser",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/402647.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-402678",
    "sku": "402678",
    "title": "Jurassic Park Claws Grn Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/402678.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-404137",
    "sku": "404137",
    "title": "Kids Lic Crew Blow Pop",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/404137.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-404125",
    "sku": "404125",
    "title": "Kids Lic Crew Hershey Bar",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/404125.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-404146",
    "sku": "404146",
    "title": "Kids Lic Crew Hershey Bar 2",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/404146.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-404148",
    "sku": "404148",
    "title": "Kids Lic Crew Reeses Pieces",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/404148.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-404079",
    "sku": "404079",
    "title": "Kids Lic Crew Smurfs",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/404079.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-404124",
    "sku": "404124",
    "title": "Kids Lic Crew Tootsie Roll",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/404124.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-404128",
    "sku": "404128",
    "title": "Kids Lic Crew Twizzlers",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/404128.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-404150",
    "sku": "404150",
    "title": "Kids Lic Crew Twizzlers (alt SKU)",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/404150.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-406776",
    "sku": "406776",
    "title": "Koze Place Grapefruit/Orange Scented Wax",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/406776.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-406775",
    "sku": "406775",
    "title": "Koze Place Woods/Amb Scented Wax",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/406775.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-383697",
    "sku": "383697",
    "title": "LED Bouncy Ball PDQ",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/383697.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-319514",
    "sku": "319514",
    "title": "Liquid Laundry Pac 10CT \u00b0 (same SKU listed twice on PP \u2014 likely one is mis-typed; check both)",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/319514.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-296803",
    "sku": "296803",
    "title": "Long Handle Lighter Candles",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/296803.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-402724",
    "sku": "402724",
    "title": "Looney Tunes Character Crew Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/402724.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-308556",
    "sku": "308556",
    "title": "Lucky Antifungal Pwdr Spray 2oz",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/308556.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-333737",
    "sku": "333737",
    "title": "Luminant Denture Brush",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/333737.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-327643",
    "sku": "327643",
    "title": "Marple Plate 8\"",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/327643.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-417437",
    "sku": "417437",
    "title": "Maybelline 4N1 Matte Med Makeup",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/417437.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-281133",
    "sku": "281133",
    "title": "Metallic Pony Beads",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/281133.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-808703",
    "sku": "808703",
    "title": "Mini Crate with Holes Clear",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/808703.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-393236",
    "sku": "393236",
    "title": "Mona Lisa Crew Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/393236.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-400726",
    "sku": "400726",
    "title": "Monroe Girls Qtr 10PK",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/400726.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-400717",
    "sku": "400717",
    "title": "Monroe Plus Legging",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/400717.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-407265",
    "sku": "407265",
    "title": "Motley Crue Wmn Crew Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/407265.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-394682",
    "sku": "394682",
    "title": "Nat Sense Diffuser Clem Basil 30ML",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/394682.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-395341",
    "sku": "395341",
    "title": "Nat Sense Tealight Lav Cham 8C",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/395341.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-397124",
    "sku": "397124",
    "title": "Oscar Mayer Crew Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/397124.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-398608",
    "sku": "398608",
    "title": "Oscar the Grouch Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/398608.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-407246",
    "sku": "407246",
    "title": "Papa Smurfs Purpl Wmn Crew Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/407246.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-400430",
    "sku": "400430",
    "title": "Paul Frank Blk Checker Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/400430.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-405736",
    "sku": "405736",
    "title": "Peppa Pig Rainbow Cereal 3.5oz",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/405736.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-405133",
    "sku": "405133",
    "title": "Poker Men Boxer Briefs",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/405133.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-411793",
    "sku": "411793",
    "title": "Popeye Gray Boxers",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/411793.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-388675",
    "sku": "388675",
    "title": "Puptarts Peanut Butter Biscuit 5oz",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/388675.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-401257",
    "sku": "401257",
    "title": "Rice Krispies Joyful Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/401257.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-354840",
    "sku": "354840",
    "title": "Safety Razor w/ 5 Blades CS",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/354840.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-403398",
    "sku": "403398",
    "title": "Sensory Bracelet",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/403398.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-402722",
    "sku": "402722",
    "title": "Sesame Street Faces Crew Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/402722.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-402721",
    "sku": "402721",
    "title": "Sesame Street Strp Faces Crew Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/402721.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-397599",
    "sku": "397599",
    "title": "Smurfs Grumpy Crew Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/397599.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-407245",
    "sku": "407245",
    "title": "Smurfs Pnk/Wht Wmn Crew Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/407245.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-401005",
    "sku": "401005",
    "title": "Spiderman Face Crew Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/401005.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-381598",
    "sku": "381598",
    "title": "Spinning Fidget Ballpoint Pen",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/381598.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-415076",
    "sku": "415076",
    "title": "Squeeze Gel Sour Astd 1.06oz",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/415076.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-417795",
    "sku": "417795",
    "title": "Sugar Cookie Mix 9.7oz",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/417795.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-402697",
    "sku": "402697",
    "title": "The Flash Tri-Color Crew Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/402697.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-416024",
    "sku": "416024",
    "title": "Vitality Chocolate Protein Shake",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/416024.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-416022",
    "sku": "416022",
    "title": "Vitality Vanilla Protein Shake 11oz",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/416022.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-284224",
    "sku": "284224",
    "title": "Welch's Fruit Punch Soda 2L",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/284224.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-284222",
    "sku": "284222",
    "title": "Welch's Pineapple Soda 2L",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/284222.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-382671",
    "sku": "382671",
    "title": "Wire Basket Astd Square BTS",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/382671.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-395861",
    "sku": "395861",
    "title": "Wizard Oil Refill Peppermint 4.5oz",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/395861.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-381083",
    "sku": "381083",
    "title": "Wizard Oil Refill Pumpkin Spice .71oz",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/381083.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-280018",
    "sku": "280018",
    "title": "Wood Beads",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/280018.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-396424",
    "sku": "396424",
    "title": "X-Men Logo Crew Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/396424.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-395760",
    "sku": "395760",
    "title": "XOXO Ladies LC 10PK",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/395760.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-395757",
    "sku": "395757",
    "title": "XOXO Ladies Qtr 10PK",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/395757.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "catalog-392016",
    "sku": "392016",
    "title": "XXL Squish Boba Animal Toy PDQ",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "fresh",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/392016.jpg",
    "dealType": "penny",
    "worthScore": 0.0,
    "note": "Penny-list reference photo for in-store matching."
  },
  {
    "id": "dh_pt27kj",
    "sku": "412418",
    "title": "Silicone Snack Topper Tray",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 9606,
    "velocity": 0.0,
    "image": "images/412418.jpg",
    "dealType": "penny",
    "worthScore": 0.7,
    "note": "Dollar Tree \u00b7 penny \u00b7 83% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_az010i",
    "sku": "379537",
    "title": "Baby Shark Body Lotion",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 8,
    "velocity": 0.0,
    "image": "images/379537.jpg",
    "dealType": "penny",
    "worthScore": 0.7,
    "note": "Dollar Tree \u00b7 penny \u00b7 83% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_lnttvi",
    "sku": "367385",
    "title": "Mr. Clean Bathroom Cleaner",
    "retailer": "Walgreens",
    "price": "$1.01",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 4,
    "velocity": 0.0,
    "image": "images/367385.jpg",
    "dealType": "unknown",
    "worthScore": 0.7,
    "note": "Walgreens \u00b7 unknown \u00b7 70% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_9qu6ec",
    "sku": "379530",
    "title": "Nickelodeon Baby Shark Baby Shampoo",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/379530.jpg",
    "dealType": "penny",
    "worthScore": 0.7,
    "note": "Dollar Tree \u00b7 penny \u00b7 90% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_ieiz2b",
    "sku": "367385",
    "title": "Scrubbing Bubbles bathroom cleaner",
    "retailer": "HEB",
    "price": "$1.00",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/367385.jpg",
    "dealType": "coupon",
    "worthScore": 0.7,
    "note": "HEB \u00b7 coupon \u00b7 75% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "m2_accept_test_001",
    "sku": "404079",
    "title": "Smurfs Kids Crew Socks",
    "retailer": "Dollar Tree",
    "price": "$0.01",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 0,
    "velocity": 0.0,
    "image": "images/404079.jpg",
    "dealType": "penny",
    "worthScore": 0.7,
    "note": "Dollar Tree \u00b7 penny \u00b7 85% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_uvpo2p",
    "sku": "",
    "title": "Gain Laundry Detergent, large size, Original Scent",
    "retailer": "Walmart",
    "price": "$9.00",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 81,
    "velocity": 0.0,
    "image": "",
    "dealType": "sale",
    "worthScore": 3.4,
    "note": "Walmart \u00b7 sale \u00b7 75% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_kv2vik",
    "sku": "",
    "title": "Gain Laundry Detergent Liquid with Odor Fighters, Original Scent, 194 fl oz, 134 Loads",
    "retailer": "Walmart",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 37,
    "velocity": 0.0,
    "image": "",
    "dealType": "sale",
    "worthScore": 3.4,
    "note": "Walmart \u00b7 sale \u00b7 96% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_jz348y",
    "sku": "",
    "title": "Palmolive Ultra Strength Liquid Dish Soap Limited Edition Original Scent 20 fl oz",
    "retailer": "Target",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 11,
    "velocity": 0.0,
    "image": "",
    "dealType": "sale",
    "worthScore": 3.4,
    "note": "Target \u00b7 sale \u00b7 93% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_zb9x7e",
    "sku": "",
    "title": "Gain Scent Beads In-Wash Scent Booster, Original, Trial Size, 5 oz",
    "retailer": "",
    "price": "$10.00",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 10,
    "velocity": 0.0,
    "image": "",
    "dealType": "unknown",
    "worthScore": 3.4,
    "note": "Unknown \u00b7 unknown \u00b7 72% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_xkf1by",
    "sku": "",
    "title": "Bounty paper towels",
    "retailer": "Walgreens",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 8,
    "velocity": 0.0,
    "image": "",
    "dealType": "unknown",
    "worthScore": 3.4,
    "note": "Walgreens \u00b7 unknown \u00b7 75% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_mov8vb",
    "sku": "",
    "title": "Dawn Dish Liquid",
    "retailer": "Walgreens",
    "price": "$1.00",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 8,
    "velocity": 0.0,
    "image": "",
    "dealType": "coupon",
    "worthScore": 3.4,
    "note": "Walgreens \u00b7 coupon \u00b7 88% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_howdrz",
    "sku": "",
    "title": "Gain Wicked For Good In-Wash Scent Booster 12.2 oz",
    "retailer": "Stop & Shop",
    "price": "$1.75",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 6,
    "velocity": 0.0,
    "image": "",
    "dealType": "clearance",
    "worthScore": 3.4,
    "note": "Stop & Shop \u00b7 clearance \u00b7 92% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_msaeb8",
    "sku": "",
    "title": "Gain 2-in-1 Laundry Detergent Original Scent",
    "retailer": "Family Dollar",
    "price": "$10.00",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 3,
    "velocity": 0.0,
    "image": "",
    "dealType": "sale",
    "worthScore": 3.4,
    "note": "Family Dollar \u00b7 sale \u00b7 80% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_dp4ddz",
    "sku": "",
    "title": "Fabuloso Multi-Purpose Cleaner Concentrated with Baking Soda",
    "retailer": "",
    "price": "",
    "was": "",
    "off": "70%",
    "freshness": "aging",
    "comments": 3,
    "velocity": 0.0,
    "image": "",
    "dealType": "clearance",
    "worthScore": 3.4,
    "note": "Unknown \u00b7 clearance \u00b7 75% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_4zbcwh",
    "sku": "",
    "title": "Gain Fabric Softener + Odor Defense Super Fresh Blast",
    "retailer": "",
    "price": "$2.00",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 0,
    "velocity": 0.0,
    "image": "",
    "dealType": "sale",
    "worthScore": 3.4,
    "note": "Unknown \u00b7 sale \u00b7 85% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_a2lzi5",
    "sku": "",
    "title": "Gain Flings Laundry Detergent Pacs, 31 Count, Moonlight Breeze, 3-in-1 HE with Oxi Boost and Febreeze",
    "retailer": "Walmart",
    "price": "$4.97",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 0,
    "velocity": 0.0,
    "image": "",
    "dealType": "clearance",
    "worthScore": 3.4,
    "note": "Walmart \u00b7 clearance \u00b7 93% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_htoha0",
    "sku": "",
    "title": "Garnier SkinActive Micellar Cleansing Water For Waterproof & Long-Wear Makeup, 13.5 fl oz",
    "retailer": "Walgreens",
    "price": "$3.40",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 0,
    "velocity": 0.0,
    "image": "",
    "dealType": "coupon",
    "worthScore": 3.4,
    "note": "Walgreens \u00b7 coupon \u00b7 96% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_agsngo",
    "sku": "",
    "title": "Gain Ultra Powder Laundry Detergent 45 oz",
    "retailer": "Walgreens",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 0,
    "velocity": 0.0,
    "image": "",
    "dealType": "clearance",
    "worthScore": 3.4,
    "note": "Walgreens \u00b7 clearance \u00b7 88% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_y7u2yv",
    "sku": "",
    "title": "Gain Happy In-Wash Scent Booster Beads, Hibiscus Hula",
    "retailer": "Family Dollar",
    "price": "$5.00",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 0,
    "velocity": 0.0,
    "image": "",
    "dealType": "coupon",
    "worthScore": 3.4,
    "note": "Family Dollar \u00b7 coupon \u00b7 80% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_g79k84",
    "sku": "",
    "title": "Gain +Odor Defense Liquid Laundry Detergent Super Fresh Blast 88 oz",
    "retailer": "CVS",
    "price": "$6.44",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 0,
    "velocity": 0.0,
    "image": "",
    "dealType": "coupon",
    "worthScore": 3.4,
    "note": "CVS \u00b7 coupon \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_7hgpbn",
    "sku": "",
    "title": "Air Wick Vibrant Essential Oil Refill White Sage & Mahogany",
    "retailer": "Dollar General",
    "price": "$3.00",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 0,
    "velocity": 0.0,
    "image": "",
    "dealType": "coupon",
    "worthScore": 3.4,
    "note": "Dollar General \u00b7 coupon \u00b7 88% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_ccnipa",
    "sku": "",
    "title": "Scrubbing Bubbles Easy Clean Foaming Toilet Bowl Cleaner",
    "retailer": "Dollar General",
    "price": "$1.03",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 0,
    "velocity": 0.0,
    "image": "",
    "dealType": "sale",
    "worthScore": 3.4,
    "note": "Dollar General \u00b7 sale \u00b7 90% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_hk4hd5",
    "sku": "",
    "title": "Gain Liquid detergent",
    "retailer": "Amazon",
    "price": "$8.40",
    "was": "",
    "off": "33%",
    "freshness": "expired",
    "comments": 107,
    "velocity": 0.0,
    "image": "",
    "dealType": "glitch",
    "worthScore": 2.0,
    "note": "Amazon \u00b7 glitch \u00b7 90% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_2dgteh",
    "sku": "",
    "title": "Dove Deep Moisture Body Wash Pump 30.6 oz",
    "retailer": "Amazon / Woot",
    "price": "$6.00",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 11,
    "velocity": 45.9,
    "image": "",
    "dealType": "glitch",
    "worthScore": 2.0,
    "note": "Amazon / Woot \u00b7 glitch \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_7n1zri",
    "sku": "",
    "title": "Gain Original Plus Laundry Detergent",
    "retailer": "Publix",
    "price": "$2.36",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 167,
    "velocity": 0.0,
    "image": "",
    "dealType": "bogo",
    "worthScore": 1.9,
    "note": "Publix \u00b7 bogo \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_s1fv48",
    "sku": "",
    "title": "Gain Beads or Detergent Mix",
    "retailer": "Publix",
    "price": "$5.00",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 89,
    "velocity": 0.0,
    "image": "",
    "dealType": "bogo",
    "worthScore": 1.9,
    "note": "Publix \u00b7 bogo \u00b7 65% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_nnhthi",
    "sku": "",
    "title": "Gain Plus Original Liquid Laundry Detergent",
    "retailer": "Publix",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 59,
    "velocity": 0.0,
    "image": "",
    "dealType": "bogo",
    "worthScore": 1.9,
    "note": "Publix \u00b7 bogo \u00b7 93% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_9is5h5",
    "sku": "",
    "title": "Gain Scent Beads fabric enhancer",
    "retailer": "Publix",
    "price": "$2.42",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 59,
    "velocity": 0.0,
    "image": "",
    "dealType": "bogo",
    "worthScore": 1.9,
    "note": "Publix \u00b7 bogo \u00b7 90% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_1qiw",
    "sku": "",
    "title": "Oscar Mayer Classic Beef Franks Hot Dogs 10 ct",
    "retailer": "Kroger",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 50,
    "velocity": 0.0,
    "image": "",
    "dealType": "bogo",
    "worthScore": 1.9,
    "note": "Kroger \u00b7 bogo \u00b7 93% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_oxuh3i",
    "sku": "",
    "title": "Gain Scent Booster 12.2 oz",
    "retailer": "Publix",
    "price": "$10.00",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 13,
    "velocity": 0.0,
    "image": "",
    "dealType": "bogo",
    "worthScore": 1.9,
    "note": "Publix \u00b7 bogo \u00b7 90% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_b0axw1",
    "sku": "",
    "title": "Gain (BOGO at Publix)",
    "retailer": "Publix",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 6,
    "velocity": 0.0,
    "image": "",
    "dealType": "bogo",
    "worthScore": 1.9,
    "note": "Publix \u00b7 bogo \u00b7 45% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_g56t8y",
    "sku": "",
    "title": "General Mills Cinnamon Toast Crunch Cereal",
    "retailer": "Kroger",
    "price": "$1.00",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 3,
    "velocity": 0.0,
    "image": "",
    "dealType": "bogo",
    "worthScore": 1.9,
    "note": "Kroger \u00b7 bogo \u00b7 92% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_xdagkq",
    "sku": "",
    "title": "Gain In-Wash Scent Booster 10.7oz / 12.2oz",
    "retailer": "",
    "price": "$10.99",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 2,
    "velocity": 0.0,
    "image": "",
    "dealType": "bogo",
    "worthScore": 1.9,
    "note": "Unknown \u00b7 bogo \u00b7 90% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_g3ggm0",
    "sku": "",
    "title": "Gain Scent Beads",
    "retailer": "",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 2,
    "velocity": 0.0,
    "image": "",
    "dealType": "bogo",
    "worthScore": 1.9,
    "note": "Unknown \u00b7 bogo \u00b7 82% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_i53ca8",
    "sku": "",
    "title": "C4 Energy Hawaiian Punch Energy Drink",
    "retailer": "Publix",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "aging",
    "comments": 0,
    "velocity": 0.0,
    "image": "",
    "dealType": "bogo",
    "worthScore": 1.9,
    "note": "Publix \u00b7 bogo \u00b7 86% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_uc0qh9",
    "sku": "",
    "title": "P&G Oral Care Products (select)",
    "retailer": "Dollar General",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 7915,
    "velocity": 0.0,
    "image": "",
    "dealType": "coupon",
    "worthScore": 0.7,
    "note": "Dollar General \u00b7 coupon \u00b7 65% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_3h8xps",
    "sku": "",
    "title": "ARM & HAMMER Baking Soda Sparkling Fresh Liquid Laundry Detergent 110 fl oz",
    "retailer": "Walmart",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 7915,
    "velocity": 0.0,
    "image": "",
    "dealType": "coupon",
    "worthScore": 0.7,
    "note": "Walmart \u00b7 coupon \u00b7 93% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_tgyq1t",
    "sku": "",
    "title": "Tom's of Maine Toothpaste",
    "retailer": "CVS",
    "price": "$10.00",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 6249,
    "velocity": 0.0,
    "image": "",
    "dealType": "coupon",
    "worthScore": 0.7,
    "note": "CVS \u00b7 coupon \u00b7 85% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_o93rv3",
    "sku": "",
    "title": "Wild Caught MSC Chilean Sea Bass Fillet",
    "retailer": "Whole Foods Market",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 1810,
    "velocity": 0.0,
    "image": "",
    "dealType": "unknown",
    "worthScore": 0.7,
    "note": "Whole Foods Market \u00b7 unknown \u00b7 92% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_5mqt6m",
    "sku": "",
    "title": "Kinder Bueno Milk Chocolate Bars 30-Count",
    "retailer": "Walmart",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 183,
    "velocity": 0.0,
    "image": "",
    "dealType": "sale",
    "worthScore": 0.7,
    "note": "Walmart \u00b7 sale \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_78c3kq",
    "sku": "",
    "title": "Crest Pro-Health Gum & Whitening Toothpaste 4.8oz",
    "retailer": "Dollar General",
    "price": "$1.94",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 115,
    "velocity": 0.0,
    "image": "",
    "dealType": "coupon",
    "worthScore": 0.7,
    "note": "Dollar General \u00b7 coupon \u00b7 96% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_5kbdue",
    "sku": "",
    "title": "Dunkin' Medium Daydream Refresher (Oat Milk, Strawberry Cold Foam, Double Strawberry)",
    "retailer": "Dunkin'",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 104,
    "velocity": 0.0,
    "image": "",
    "dealType": "unknown",
    "worthScore": 0.7,
    "note": "Dunkin' \u00b7 unknown \u00b7 87% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_2ojgcz",
    "sku": "",
    "title": "Mr. Clean cleaner",
    "retailer": "Dollar General",
    "price": "$1.00",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 80,
    "velocity": 0.0,
    "image": "",
    "dealType": "coupon",
    "worthScore": 0.7,
    "note": "Dollar General \u00b7 coupon \u00b7 85% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_2dugqo",
    "sku": "",
    "title": "Crest Pro-Health + Scope Toothpaste 4.3 oz",
    "retailer": "Dollar General",
    "price": "$2.00",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 79,
    "velocity": 0.0,
    "image": "",
    "dealType": "coupon",
    "worthScore": 0.7,
    "note": "Dollar General \u00b7 coupon \u00b7 88% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_1ptu1v",
    "sku": "",
    "title": "Oral-B Glide Mint Dental Floss Picks",
    "retailer": "Dollar General",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 72,
    "velocity": 0.0,
    "image": "",
    "dealType": "coupon",
    "worthScore": 0.7,
    "note": "Dollar General \u00b7 coupon \u00b7 87% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_b6e7z2",
    "sku": "",
    "title": "Gain Happy Laundry Detergent, 100 loads",
    "retailer": "Family Dollar",
    "price": "$3.00",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 47,
    "velocity": 0.0,
    "image": "",
    "dealType": "clearance",
    "worthScore": 0.7,
    "note": "Family Dollar \u00b7 clearance \u00b7 97% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_iwn3gx",
    "sku": "",
    "title": "Glacier Bay Bathroom Vanity",
    "retailer": "Home Depot",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 45,
    "velocity": 0.0,
    "image": "",
    "dealType": "clearance",
    "worthScore": 0.7,
    "note": "Home Depot \u00b7 clearance \u00b7 62% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_z7tdmx",
    "sku": "",
    "title": "Gain Dryer Sheets Moonlight Breeze 60 count",
    "retailer": "Walgreens",
    "price": "",
    "was": "",
    "off": "10%",
    "freshness": "expired",
    "comments": 38,
    "velocity": 0.0,
    "image": "",
    "dealType": "coupon",
    "worthScore": 0.7,
    "note": "Walgreens \u00b7 coupon \u00b7 98% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_i1expw",
    "sku": "",
    "title": "Tide Ultra Sport Liquid Laundry Detergent, 74 loads, 105 fl oz",
    "retailer": "Walmart",
    "price": "$4.00",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 32,
    "velocity": 0.0,
    "image": "",
    "dealType": "clearance",
    "worthScore": 0.7,
    "note": "Walmart \u00b7 clearance \u00b7 92% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_fdfift",
    "sku": "",
    "title": "Gain Pods",
    "retailer": "Dollar General",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 21,
    "velocity": 0.0,
    "image": "",
    "dealType": "clearance",
    "worthScore": 0.7,
    "note": "Dollar General \u00b7 clearance \u00b7 80% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_712gf3",
    "sku": "",
    "title": "Madden NYC Women's Moto Wrist Boot",
    "retailer": "",
    "price": "$1.00",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 19,
    "velocity": 0.0,
    "image": "",
    "dealType": "clearance",
    "worthScore": 0.7,
    "note": "Unknown \u00b7 clearance \u00b7 83% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_108x33",
    "sku": "",
    "title": "Igloo cooler 30qt",
    "retailer": "Dollar General",
    "price": "$1.00",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 15,
    "velocity": 0.0,
    "image": "",
    "dealType": "sale",
    "worthScore": 0.7,
    "note": "Dollar General \u00b7 sale \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_hi6iwj",
    "sku": "",
    "title": "Carter's Child of Mine Pink Onesie Romper",
    "retailer": "Walmart",
    "price": "$1.00",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 14,
    "velocity": 0.0,
    "image": "",
    "dealType": "clearance",
    "worthScore": 0.7,
    "note": "Walmart \u00b7 clearance \u00b7 92% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_j0o40z",
    "sku": "",
    "title": "Gain Flings Laundry Detergent Pacs, 31 Count, Moonlight Breeze",
    "retailer": "Walmart",
    "price": "$4.97",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 10,
    "velocity": 0.0,
    "image": "",
    "dealType": "sale",
    "worthScore": 0.7,
    "note": "Walmart \u00b7 sale \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_dtq9it",
    "sku": "",
    "title": "Tide Spring Meadow HE Laundry Detergent Pods 20ct 15oz",
    "retailer": "",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 8,
    "velocity": 0.0,
    "image": "",
    "dealType": "sale",
    "worthScore": 0.7,
    "note": "Unknown \u00b7 sale \u00b7 88% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_fhcttq",
    "sku": "",
    "title": "Metal Raceway",
    "retailer": "",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 7,
    "velocity": 0.0,
    "image": "",
    "dealType": "unknown",
    "worthScore": 0.7,
    "note": "Unknown \u00b7 unknown \u00b7 88% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_qdvhw0",
    "sku": "",
    "title": "Gain Plus Liquid Laundry Detergent",
    "retailer": "Dollar General",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 6,
    "velocity": 0.0,
    "image": "",
    "dealType": "sale",
    "worthScore": 0.7,
    "note": "Dollar General \u00b7 sale \u00b7 83% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_jdcbnb",
    "sku": "",
    "title": "Gain Laundry Detergent Sheets",
    "retailer": "Dollar General",
    "price": "$5.00",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 6,
    "velocity": 0.0,
    "image": "",
    "dealType": "coupon",
    "worthScore": 0.7,
    "note": "Dollar General \u00b7 coupon \u00b7 75% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_dwiz6t",
    "sku": "",
    "title": "Gain Scent Boosters",
    "retailer": "Family Dollar",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 6,
    "velocity": 0.0,
    "image": "",
    "dealType": "sale",
    "worthScore": 0.7,
    "note": "Family Dollar \u00b7 sale \u00b7 80% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_6nyq3z",
    "sku": "",
    "title": "TP-Link RE305 AC1200 Mesh Wi-Fi Range Extender",
    "retailer": "",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 5,
    "velocity": 0.0,
    "image": "",
    "dealType": "clearance",
    "worthScore": 0.7,
    "note": "Unknown \u00b7 clearance \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_erwhxq",
    "sku": "",
    "title": "Softsoap Body Wash Pomegranate & Mango 20 oz",
    "retailer": "CVS",
    "price": "$0.83",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 4,
    "velocity": 0.0,
    "image": "",
    "dealType": "coupon",
    "worthScore": 0.7,
    "note": "CVS \u00b7 coupon \u00b7 97% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_cvwc6w",
    "sku": "",
    "title": "Space Explorer Graphic Short Sleeve Shirt",
    "retailer": "Walmart",
    "price": "$3.00",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 4,
    "velocity": 0.0,
    "image": "",
    "dealType": "clearance",
    "worthScore": 0.7,
    "note": "Walmart \u00b7 clearance \u00b7 78% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_8nu893",
    "sku": "",
    "title": "Gain Fabric Softener",
    "retailer": "CVS",
    "price": "$1.00",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 4,
    "velocity": 0.0,
    "image": "",
    "dealType": "clearance",
    "worthScore": 0.7,
    "note": "CVS \u00b7 clearance \u00b7 93% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_8q84xh",
    "sku": "",
    "title": "Gain Dryer Sheets",
    "retailer": "Walgreens",
    "price": "$0.79",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 4,
    "velocity": 0.0,
    "image": "",
    "dealType": "coupon",
    "worthScore": 0.7,
    "note": "Walgreens \u00b7 coupon \u00b7 80% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  },
  {
    "id": "dh_gbf26m",
    "sku": "",
    "title": "Tide Ultra Hygienic Clean",
    "retailer": "Walgreens",
    "price": "",
    "was": "",
    "off": "",
    "freshness": "expired",
    "comments": 4,
    "velocity": 0.0,
    "image": "",
    "dealType": "clearance",
    "worthScore": 0.7,
    "note": "Walgreens \u00b7 clearance \u00b7 92% extraction confidence. Source-only fields are omitted from this public staging snapshot."
  }
];
