window.STAGING_SNAPSHOT = {
  "generatedAt": "2026-06-13T15:32:06Z",
  "source": "deal-hunter local DB + penny catalog local thumbnails",
  "count": 107,
  "imageCount": 32,
  "deals": [
    {
      "id": "02b863c4-443d-4117-a51d-12426c011781",
      "sku": "",
      "title": "Charmin Ultra Strong Toilet Paper 16 Mega XL",
      "retailer": "Kroger",
      "price": "$19.49",
      "was": "$27.49",
      "off": "29%",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "coupon",
      "worthScore": 0.0,
      "note": "Kroger \u00b7 coupon \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "02bd499d-1329-4c69-a9fd-ac17f816b6f9",
      "sku": "",
      "title": "Casey's Frost Bite Medium Frozen Drink",
      "retailer": "Casey's",
      "price": "$0",
      "was": "",
      "off": "100%",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 0.0,
      "note": "Casey's \u00b7 sale \u00b7 85% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "095cc6fe-cb9b-42f9-a67a-c751906d35da",
      "sku": "",
      "title": "Coca-Cola Zero Sugar Cherry Soda 6 pack",
      "retailer": "Kroger",
      "price": "$7.49",
      "was": "$22.47",
      "off": "67%",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 0.0,
      "note": "Kroger \u00b7 sale \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "204f98ef-0f09-43f6-831b-577304f97d7b",
      "sku": "",
      "title": "Bridgerton Dearest Tempting Peach Eau de Parfum 1.6 oz",
      "retailer": "Ulta",
      "price": "$30",
      "was": "$120",
      "off": "75%",
      "freshness": "fresh",
      "comments": 1,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 0.0,
      "note": "Ulta \u00b7 sale \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "29abeae3-9f9d-47da-b8dc-289eb6337419",
      "sku": "",
      "title": "Ulta Platinum Exclusive 15% coupon",
      "retailer": "Ulta",
      "price": "",
      "was": "",
      "off": "15%",
      "freshness": "fresh",
      "comments": 1,
      "velocity": 0.0,
      "image": "",
      "dealType": "coupon",
      "worthScore": 0.0,
      "note": "Ulta \u00b7 coupon \u00b7 90% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "7a4bf9e2-e22b-4309-a15b-1eb94afc8025",
      "sku": "",
      "title": "Colgate Optic White Soft Charcoal Toothbrush",
      "retailer": "Kroger",
      "price": "$1.99",
      "was": "$6.79",
      "off": "71%",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "coupon",
      "worthScore": 0.0,
      "note": "Kroger \u00b7 coupon \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "8126f6d7-9740-41f8-bf5c-e3739b453ed8",
      "sku": "",
      "title": "Colgate MaxFresh Clean Mint Toothpaste",
      "retailer": "Kroger",
      "price": "$0",
      "was": "$4.19",
      "off": "100%",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "coupon",
      "worthScore": 0.0,
      "note": "Kroger \u00b7 coupon \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "a1ea57d3-46da-4f13-968e-e11ec71003cc",
      "sku": "",
      "title": "Garnier Fructis Sleek & Shine Smoothing Conditioner",
      "retailer": "Kroger",
      "price": "$2.38",
      "was": "$8.38",
      "off": "72%",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "coupon",
      "worthScore": 0.0,
      "note": "Kroger \u00b7 coupon \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "b29991e6-33b1-4387-af18-b52e037a1ab8",
      "sku": "",
      "title": "Kroger Purified Bottled Water 24 pack",
      "retailer": "Kroger",
      "price": "$11.07",
      "was": "$22.14",
      "off": "50%",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 0.0,
      "note": "Kroger \u00b7 sale \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "e294ca1f-a276-4206-b049-ddac7972f249",
      "sku": "",
      "title": "Sprite Lemon-Lime Caffeine Free Soda 6 pack",
      "retailer": "Kroger",
      "price": "$7.49",
      "was": "$14.98",
      "off": "50%",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 0.0,
      "note": "Kroger \u00b7 sale \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "fe851f20-130f-4aff-85a1-e318d1ef9c32",
      "sku": "",
      "title": "Bridgerton Dearest Graceful Hydrangea Eau de Parfum 1.6 oz",
      "retailer": "Ulta",
      "price": "$15",
      "was": "$60",
      "off": "75%",
      "freshness": "fresh",
      "comments": 1,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 0.0,
      "note": "Ulta \u00b7 sale \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "0344daec-fc30-4908-80a9-ba1830c29226",
      "sku": "",
      "title": "Suave Hyaluronic Infusion",
      "retailer": "Unknown",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "fresh",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "unknown",
      "worthScore": 0.0,
      "note": "Unknown \u00b7 unknown \u00b7 82% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "06c8c647-833d-410f-bae4-f6462a100986",
      "sku": "",
      "title": "Refresh Auto Vent Clip Air Freshener",
      "retailer": "Unknown",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "fresh",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "unknown",
      "worthScore": 0.0,
      "note": "Unknown \u00b7 unknown \u00b7 72% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "1744c4af-03bf-4cff-9d06-7cc5261e274b",
      "sku": "",
      "title": "OxiClean 3-in-1 Deep Clean Spray",
      "retailer": "Unknown",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "fresh",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "unknown",
      "worthScore": 0.0,
      "note": "Unknown \u00b7 unknown \u00b7 88% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "18443253-7ae2-4224-993d-75b8f6c17a8f",
      "sku": "",
      "title": "Garnier Micellar Cleansing Water",
      "retailer": "Unknown",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "fresh",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "unknown",
      "worthScore": 0.0,
      "note": "Unknown \u00b7 unknown \u00b7 78% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "3c885f1d-2c6b-436b-904a-07b060814323",
      "sku": "",
      "title": "Clorox",
      "retailer": "Unknown",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "fresh",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "unknown",
      "worthScore": 0.0,
      "note": "Unknown \u00b7 unknown \u00b7 70% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "58c2175c-c2d7-42b8-984d-fff77a94d20f",
      "sku": "",
      "title": "L'Oreal Paris Collagen Moisture Filler Daily Moisturizer 1.7 oz",
      "retailer": "Unknown",
      "price": "$9.85",
      "was": "",
      "off": "",
      "freshness": "fresh",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "clearance",
      "worthScore": 0.0,
      "note": "Unknown \u00b7 clearance \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "5ae75274-c025-4668-8331-d915e36ee1f7",
      "sku": "",
      "title": "Truebluing Blissful Berry Air Freshener",
      "retailer": "Unknown",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "fresh",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "unknown",
      "worthScore": 0.0,
      "note": "Unknown \u00b7 unknown \u00b7 78% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "6e0d0ed7-3e71-4b95-ac57-f0478033c7e1",
      "sku": "",
      "title": "Root Touch-Up Hair Color",
      "retailer": "Unknown",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "fresh",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "clearance",
      "worthScore": 0.0,
      "note": "Unknown \u00b7 clearance \u00b7 52% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "81355158-3d0a-48c5-9684-9884d2dfcd91",
      "sku": "",
      "title": "Lysol",
      "retailer": "Unknown",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "fresh",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "unknown",
      "worthScore": 0.0,
      "note": "Unknown \u00b7 unknown \u00b7 70% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "822ae5af-e93f-4463-9349-753b5b5f9907",
      "sku": "",
      "title": "Fabuloso Multi-Purpose Cleaner Concentrated Formula with Baking Soda",
      "retailer": "Unknown",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "unknown",
      "worthScore": 0.0,
      "note": "Unknown \u00b7 unknown \u00b7 83% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "8f0dbf29-78c9-494c-89de-6addf82d4af4",
      "sku": "",
      "title": "Air Wick Vibrant Scented Oil Refills White Sage & Mahogany 3-Pack",
      "retailer": "Unknown",
      "price": "$7.50",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "clearance",
      "worthScore": 0.0,
      "note": "Unknown \u00b7 clearance \u00b7 92% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "91c100fd-3080-414a-990b-1b2f6c88e2ba",
      "sku": "",
      "title": "Zevo Insect Spray",
      "retailer": "Unknown",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "unknown",
      "worthScore": 0.0,
      "note": "Unknown \u00b7 unknown \u00b7 45% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "a90b072d-b6d7-4f3e-aade-3a2a7ec4a881",
      "sku": "",
      "title": "Olay Body Lotion",
      "retailer": "Unknown",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "unknown",
      "worthScore": 0.0,
      "note": "Unknown \u00b7 unknown \u00b7 55% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "ba7e3614-0ec4-461a-8abb-ff85641fc544",
      "sku": "",
      "title": "BIC Comfort 3 Disposable Razors",
      "retailer": "Unknown",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "unknown",
      "worthScore": 0.0,
      "note": "Unknown \u00b7 unknown \u00b7 82% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "bcdb7622-bc98-4d17-817b-0e3089d6706f",
      "sku": "",
      "title": "Dove Love Your Silver Gorgeous Grays Ultra-Light Conditioner 13.5 oz",
      "retailer": "Unknown",
      "price": "$6",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "clearance",
      "worthScore": 0.0,
      "note": "Unknown \u00b7 clearance \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "daf4af30-6af3-4e8c-ba03-c5d1656babb4",
      "sku": "",
      "title": "Schick Hydro Sensitive Razor Blade Refills Value Pack 6-Count",
      "retailer": "Unknown",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "unknown",
      "worthScore": 0.0,
      "note": "Unknown \u00b7 unknown \u00b7 88% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "ec0b40c8-69c3-4587-8c8d-9ecef04735b4",
      "sku": "",
      "title": "OxiClean 3-in-1 Deep Clean",
      "retailer": "Unknown",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "unknown",
      "worthScore": 0.0,
      "note": "Unknown \u00b7 unknown \u00b7 80% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "fcf35c06-6b15-441b-9a21-0a928e108adf",
      "sku": "",
      "title": "Canned Salmon",
      "retailer": "Unknown",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "unknown",
      "worthScore": 0.0,
      "note": "Unknown \u00b7 unknown \u00b7 50% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "058c43fe-aab9-4be9-ba30-3266bd72f6d1",
      "sku": "",
      "title": "Clorox Toilet Bowl Cleaner Clinging Bleach Gel",
      "retailer": "Dollar General",
      "price": "$1.58",
      "was": "$5.27",
      "off": "",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 6.85,
      "note": "Dollar General \u00b7 sale \u00b7 88% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "12824ea9-2915-429a-80e3-99f2c8c29e23",
      "sku": "",
      "title": "Air Wick Vibrant Scented Oil 3 Refills White Sage & Mahogany",
      "retailer": "Dollar General",
      "price": "$7.50",
      "was": "",
      "off": "",
      "freshness": "fresh",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "clearance",
      "worthScore": 6.85,
      "note": "Dollar General \u00b7 clearance \u00b7 80% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "1d965c0e-dfee-42ca-8b22-38e7b40f903e",
      "sku": "",
      "title": "OUT! Pet Care Stain & Odor Remover Spray",
      "retailer": "Dollar General",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 0.0,
      "note": "Dollar General \u00b7 sale \u00b7 72% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "2b5e01f1-f78b-4b4d-991c-1d63c679ef62",
      "sku": "",
      "title": "Clorox Scentiva Disinfecting Wipes",
      "retailer": "Dollar General",
      "price": "$1.49",
      "was": "$4.95",
      "off": "",
      "freshness": "aging",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 0.0,
      "note": "Dollar General \u00b7 sale \u00b7 82% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "365a257f-5d91-4bd7-ba5e-084a49183305",
      "sku": "",
      "title": "Clorox Toilet Bowl Cleaner Value Pack",
      "retailer": "Dollar General",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "coupon",
      "worthScore": 0.0,
      "note": "Dollar General \u00b7 coupon \u00b7 90% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "445536d2-2aca-4d72-b78b-ea391ada7a65",
      "sku": "",
      "title": "Suave Hyaluronic Infusion Conditioner",
      "retailer": "Unknown",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "fresh",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "clearance",
      "worthScore": 6.85,
      "note": "Unknown \u00b7 clearance \u00b7 78% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "4ff5c633-d2ef-4756-973c-8fc0f08551ec",
      "sku": "",
      "title": "Crest 3D White Stain Eraser Whitening Toothpaste",
      "retailer": "Dollar General",
      "price": "$0.39",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 0.0,
      "note": "Dollar General \u00b7 sale \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "6615855e-b0f8-4acf-8b6c-4ed36a8c5f16",
      "sku": "",
      "title": "Scrubbing Bubbles Easy Clean Multi-Purpose Foam",
      "retailer": "Dollar General",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "coupon",
      "worthScore": 0.0,
      "note": "Dollar General \u00b7 coupon \u00b7 90% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "71568a0f-8318-46b0-8513-15d498a99dbb",
      "sku": "",
      "title": "Febreze Plug In Air Freshener Scented Oil Warmer Device",
      "retailer": "Walgreens",
      "price": "$1.49",
      "was": "$4.99",
      "off": "",
      "freshness": "aging",
      "comments": 1,
      "velocity": 0.0,
      "image": "",
      "dealType": "coupon",
      "worthScore": 0.0,
      "note": "Walgreens \u00b7 coupon \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "73731292-7b0b-4de0-a352-4b10b62a01ee",
      "sku": "",
      "title": "Fabuloso Multi-Purpose Cleaner Concentrated with Baking Soda",
      "retailer": "Unknown",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "fresh",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "clearance",
      "worthScore": 6.85,
      "note": "Unknown \u00b7 clearance \u00b7 75% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "7ff1f0c7-122c-4d17-84f9-81341dc76d03",
      "sku": "",
      "title": "Olay Firming Body Lotion",
      "retailer": "Unknown",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "fresh",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "clearance",
      "worthScore": 6.85,
      "note": "Unknown \u00b7 clearance \u00b7 88% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "9189ed41-6a85-4347-a653-e3dc6c8e7757",
      "sku": "",
      "title": "Crest 3D White Fresh Whitening Mouthwash",
      "retailer": "Dollar General",
      "price": "$0",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 0.0,
      "note": "Dollar General \u00b7 sale \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "9bf3bb6c-d857-4e74-b6de-ea12d79f7a99",
      "sku": "",
      "title": "Schick Hydro Sensitive Razor Refills Value Pack 6ct",
      "retailer": "Unknown",
      "price": "$2.67",
      "was": "",
      "off": "",
      "freshness": "fresh",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "clearance",
      "worthScore": 6.85,
      "note": "Unknown \u00b7 clearance \u00b7 90% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "9cb3470d-3163-458a-8fcf-91db4b3e6e80",
      "sku": "",
      "title": "Scrubbing Bubbles Easy Clean Foaming Toilet Bowl Cleaner",
      "retailer": "Dollar General",
      "price": "$1.13",
      "was": "$3.75",
      "off": "",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 6.85,
      "note": "Dollar General \u00b7 sale \u00b7 90% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "a97ac929-cd6e-4228-a8e7-43eaf8adbbf6",
      "sku": "",
      "title": "Scrubbing Bubbles Easy Clean Multi-Purpose Foam Spray",
      "retailer": "Dollar General",
      "price": "$1.35",
      "was": "$4.50",
      "off": "",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 6.85,
      "note": "Dollar General \u00b7 sale \u00b7 87% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "aabc247d-374b-429d-a67d-3068f1ae0792",
      "sku": "",
      "title": "OxiClean 3-in-1 Deep Clean Multi-Purpose Spray",
      "retailer": "Dollar General",
      "price": "$1.03",
      "was": "$4.05",
      "off": "",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 6.85,
      "note": "Dollar General \u00b7 sale \u00b7 90% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "ba9d010f-32a8-40e7-a61f-acd151252d13",
      "sku": "",
      "title": "Crest 3D White Advanced Teeth Whitening Toothpaste",
      "retailer": "Dollar General",
      "price": "$0.50",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 0.0,
      "note": "Dollar General \u00b7 sale \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "c1580e58-7021-45e1-bf4c-afe3e8f3c78b",
      "sku": "",
      "title": "L'Oreal Paris Magic Root Cover Up Hair Color",
      "retailer": "Unknown",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "fresh",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "clearance",
      "worthScore": 6.85,
      "note": "Unknown \u00b7 clearance \u00b7 72% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "d70adea8-9e0f-4da6-aa15-603e0090196a",
      "sku": "",
      "title": "Lysol Disinfecting Wipes",
      "retailer": "Dollar General",
      "price": "$3.51",
      "was": "$11.70",
      "off": "",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 6.85,
      "note": "Dollar General \u00b7 sale \u00b7 88% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "d80cf366-875c-47d8-a6c0-deb00a5995d9",
      "sku": "",
      "title": "Crest 3D White Brilliance Deep Stain Remover Toothpaste Dazzling Mint",
      "retailer": "Dollar General",
      "price": "$1.53",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 0.0,
      "note": "Dollar General \u00b7 sale \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "e02c53f9-81b8-4c9b-8dfb-3667ccc8ea4d",
      "sku": "",
      "title": "Oral-B Essential Clean Soft Toothbrushes 6ct",
      "retailer": "Dollar General",
      "price": "$1.02",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 0.0,
      "note": "Dollar General \u00b7 sale \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "f02c91f8-bd8a-474e-9935-a9bfe4288f41",
      "sku": "",
      "title": "2Boom LED Touch Bluetooth Speaker with FM Radio",
      "retailer": "Dollar General",
      "price": "$4.50",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "clearance",
      "worthScore": 0.0,
      "note": "Dollar General \u00b7 clearance \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "f05d2ed2-8495-4400-822e-3746d255e08b",
      "sku": "",
      "title": "7-Eleven Whole Pizza",
      "retailer": "7-Eleven",
      "price": "$0.11",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 4,
      "velocity": 0.0,
      "image": "",
      "dealType": "glitch",
      "worthScore": 0.0,
      "note": "7-Eleven \u00b7 glitch \u00b7 92% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "f67623dd-06a2-405d-a7f3-65a5b6d3796d",
      "sku": "",
      "title": "OxiClean 3-in-1 Deep Clean Multi-Purpose Spray",
      "retailer": "Unknown",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "fresh",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "clearance",
      "worthScore": 6.85,
      "note": "Unknown \u00b7 clearance \u00b7 75% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "0274cf34-426b-4bef-9909-8d2bae73b317",
      "sku": "",
      "title": "Air Wick Vibrant Essential Oil Refill White Sage & Mahogany",
      "retailer": "Dollar General",
      "price": "$3.75",
      "was": "",
      "off": "",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "coupon",
      "worthScore": 6.85,
      "note": "Dollar General \u00b7 coupon \u00b7 88% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "2f2381a5-0c18-4468-be4f-9a8637c122bc",
      "sku": "",
      "title": "Diapers",
      "retailer": "Dollar General",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "unknown",
      "worthScore": 6.85,
      "note": "Dollar General \u00b7 unknown \u00b7 42% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "63d08bf9-547d-4a64-947d-0f025b0b0e45",
      "sku": "",
      "title": "Garnier Micellar Cleansing Water (large)",
      "retailer": "Dollar General",
      "price": "$1.35",
      "was": "",
      "off": "",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "coupon",
      "worthScore": 6.85,
      "note": "Dollar General \u00b7 coupon \u00b7 90% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "86ace40f-09d9-44b3-9240-f9a41b3c77b6",
      "sku": "",
      "title": "Garnier Micellar Facial Cleanser (small)",
      "retailer": "Dollar General",
      "price": "$0.60",
      "was": "$4",
      "off": "",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "coupon",
      "worthScore": 6.85,
      "note": "Dollar General \u00b7 coupon \u00b7 88% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "9f029933-e607-4fba-a7ac-635542e617e9",
      "sku": "",
      "title": "Canned Salmon",
      "retailer": "Dollar General",
      "price": "$1.41",
      "was": "",
      "off": "",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 6.85,
      "note": "Dollar General \u00b7 sale \u00b7 82% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "abe11722-a52b-448b-b11a-a38d718aea53",
      "sku": "",
      "title": "Olay Firming Body Lotion Collagen Peptide 17 fl oz",
      "retailer": "Dollar General",
      "price": "$1.65",
      "was": "$11",
      "off": "",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "coupon",
      "worthScore": 6.85,
      "note": "Dollar General \u00b7 coupon \u00b7 97% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "b6fb6368-7b58-4782-9985-ba659a03f83b",
      "sku": "",
      "title": "Via Body Oil Turmeric",
      "retailer": "Dollar General",
      "price": "$0.15",
      "was": "$1",
      "off": "",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "coupon",
      "worthScore": 6.85,
      "note": "Dollar General \u00b7 coupon \u00b7 87% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "c218d0fb-a560-4a41-8c07-ae5a81582209",
      "sku": "",
      "title": "Dove Beauty Bar Soap",
      "retailer": "Dollar General",
      "price": "$1.95",
      "was": "",
      "off": "",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 6.85,
      "note": "Dollar General \u00b7 sale \u00b7 88% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "c8225b83-06b9-46f4-95f3-5fb27e1ed7a7",
      "sku": "",
      "title": "Via Body Oil Neem",
      "retailer": "Dollar General",
      "price": "$0.15",
      "was": "$1",
      "off": "",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "coupon",
      "worthScore": 6.85,
      "note": "Dollar General \u00b7 coupon \u00b7 83% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "c83a44e0-d9b4-40bf-b809-51e7176110e7",
      "sku": "",
      "title": "Clairol Root Touch-Up ColorBlend Dark Brown Hair Color",
      "retailer": "Dollar General",
      "price": "$1.45",
      "was": "$3.45",
      "off": "",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "clearance",
      "worthScore": 6.85,
      "note": "Dollar General \u00b7 clearance \u00b7 92% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "dab29eba-6d76-413e-a648-8b3ec1d83caf",
      "sku": "",
      "title": "Schick Hydro5 Sensitive Cartridges Value Pack 6",
      "retailer": "Dollar General",
      "price": "$2.25",
      "was": "$15",
      "off": "",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "coupon",
      "worthScore": 6.85,
      "note": "Dollar General \u00b7 coupon \u00b7 95% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "dee1cc6a-54f6-4e6e-8555-1cdfed66f9f0",
      "sku": "",
      "title": "Suave Shampoo or Conditioner",
      "retailer": "Dollar General",
      "price": "$1.88",
      "was": "",
      "off": "",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 6.85,
      "note": "Dollar General \u00b7 sale \u00b7 78% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "f9d1466f-40ef-44b5-afa3-2ba64093c6f7",
      "sku": "",
      "title": "Decorative Wicker Storage Basket",
      "retailer": "Dollar General",
      "price": "$3",
      "was": "$6",
      "off": "",
      "freshness": "fresh",
      "comments": 0,
      "velocity": 0.0,
      "image": "",
      "dealType": "coupon",
      "worthScore": 6.85,
      "note": "Dollar General \u00b7 coupon \u00b7 85% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "01263903-998a-4c05-8fcb-9530a5780906",
      "sku": "",
      "title": "Gain Liquid Laundry Detergent",
      "retailer": "Walgreens",
      "price": "$15.99",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 1,
      "velocity": 0.0,
      "image": "",
      "dealType": "coupon",
      "worthScore": 3.43,
      "note": "Walgreens \u00b7 coupon \u00b7 90% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "03b32518-7a7a-4d21-bd56-ba69e22be887",
      "sku": "",
      "title": "Tide Oxi Boost Liquid Laundry Detergent",
      "retailer": "Dollar General",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 49,
      "velocity": 0.0,
      "image": "",
      "dealType": "coupon",
      "worthScore": 3.43,
      "note": "Dollar General \u00b7 coupon \u00b7 70% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "0e8d653d-5ed4-4439-9570-c5444c6a779e",
      "sku": "",
      "title": "Crest Pro-Health Clean Mint Mouthwash",
      "retailer": "Walgreens",
      "price": "$6",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 1,
      "velocity": 0.0,
      "image": "",
      "dealType": "coupon",
      "worthScore": 3.43,
      "note": "Walgreens \u00b7 coupon \u00b7 88% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "17d91599-e95f-4734-8f1d-67a42d459b4e",
      "sku": "",
      "title": "Clorox Clean-Up Cleaner Spray",
      "retailer": "Dollar General",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 49,
      "velocity": 0.0,
      "image": "",
      "dealType": "coupon",
      "worthScore": 3.43,
      "note": "Dollar General \u00b7 coupon \u00b7 70% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "1da24353-ad1c-4616-a709-862787710bf9",
      "sku": "",
      "title": "Gain Liquid Fabric Softener",
      "retailer": "Dollar General",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 49,
      "velocity": 0.0,
      "image": "",
      "dealType": "coupon",
      "worthScore": 3.43,
      "note": "Dollar General \u00b7 coupon \u00b7 72% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "260c8cfa-3067-4845-82c8-d186a9ad8764",
      "sku": "",
      "title": "Gain 2-in-1 Laundry Detergent Original Scent",
      "retailer": "Family Dollar",
      "price": "$3.33",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 3.43,
      "note": "Family Dollar \u00b7 sale \u00b7 80% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "2a950765-5268-4c9b-960d-b5df50adf341",
      "sku": "",
      "title": "Gain + Ultra Oxi Laundry Detergent Pods Flings",
      "retailer": "Dollar General",
      "price": "",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 49,
      "velocity": 0.0,
      "image": "",
      "dealType": "coupon",
      "worthScore": 3.43,
      "note": "Dollar General \u00b7 coupon \u00b7 78% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "310bcffd-d509-45a4-8b1f-7d3e35a8cd27",
      "sku": "",
      "title": "Gain Wicked For Good In-Wash Scent Booster 12.2 oz",
      "retailer": "Stop & Shop",
      "price": "$5.50",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 6,
      "velocity": 0.0,
      "image": "",
      "dealType": "clearance",
      "worthScore": 3.43,
      "note": "Stop & Shop \u00b7 clearance \u00b7 92% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "3a093034-79b2-4e5d-b422-86912ff72d77",
      "sku": "",
      "title": "Gain 2-in-1 Laundry Detergent Midnight Breeze",
      "retailer": "Family Dollar",
      "price": "$3.33",
      "was": "",
      "off": "",
      "freshness": "aging",
      "comments": 3,
      "velocity": 0.0,
      "image": "",
      "dealType": "sale",
      "worthScore": 3.43,
      "note": "Family Dollar \u00b7 sale \u00b7 82% extraction confidence. Source-only fields are omitted from this public staging snapshot."
    },
    {
      "id": "catalog-390887",
      "sku": "390887",
      "title": "Elmo Black Crew Socks",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/390887.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-393236",
      "sku": "393236",
      "title": "Mona Lisa Crew Socks",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/393236.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-395757",
      "sku": "395757",
      "title": "XOXO Ladies Qtr 10PK",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/395757.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-395760",
      "sku": "395760",
      "title": "XOXO Ladies LC 10PK",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/395760.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-396424",
      "sku": "396424",
      "title": "X-Men Logo Crew Socks",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/396424.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-397121",
      "sku": "397121",
      "title": "Mountain Dew Crew Socks",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/397121.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-397124",
      "sku": "397124",
      "title": "Oscar Mayer Crew Socks",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/397124.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-397126",
      "sku": "397126",
      "title": "Kool-Aid Men's Crew Socks",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/397126.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-397599",
      "sku": "397599",
      "title": "Smurfs Grumpy Crew Socks",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/397599.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-397740",
      "sku": "397740",
      "title": "Cheez-It Crew Socks",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/397740.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-398608",
      "sku": "398608",
      "title": "Oscar the Grouch Socks",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/398608.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-400430",
      "sku": "400430",
      "title": "Paul Frank Blk Checker Socks",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/400430.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-400717",
      "sku": "400717",
      "title": "Monroe Plus Legging",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/400717.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-400726",
      "sku": "400726",
      "title": "Monroe Girls Qtr 10PK",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/400726.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-401005",
      "sku": "401005",
      "title": "Spiderman Face Crew Socks",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/401005.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-401257",
      "sku": "401257",
      "title": "Rice Krispies Joyful Socks",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/401257.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-402677",
      "sku": "402677",
      "title": "Elmo Crew Socks",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/402677.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-402678",
      "sku": "402678",
      "title": "Jurassic Park Claws Grn Socks",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/402678.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-402696",
      "sku": "402696",
      "title": "Elmo Crayons Red Crew Socks",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/402696.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-402697",
      "sku": "402697",
      "title": "The Flash Tri-Color Crew Socks",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/402697.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-402718",
      "sku": "402718",
      "title": "Bugs Bunny Gry Stripe Crew Socks",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/402718.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-402721",
      "sku": "402721",
      "title": "Sesame Street Strp Faces Crew Socks",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/402721.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-402722",
      "sku": "402722",
      "title": "Sesame Street Faces Crew Socks",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/402722.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-402724",
      "sku": "402724",
      "title": "Looney Tunes Character Crew Socks",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/402724.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-403094",
      "sku": "403094",
      "title": "E.T. Bicycle Crew Socks",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/403094.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-404124",
      "sku": "404124",
      "title": "Kids Lic Crew Tootsie Roll",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/404124.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-404125",
      "sku": "404125",
      "title": "Kids Lic Crew Hershey Bar",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/404125.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-404128",
      "sku": "404128",
      "title": "Kids Lic Crew Twizzlers",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/404128.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-404137",
      "sku": "404137",
      "title": "Kids Lic Crew Blow Pop",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/404137.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-404140",
      "sku": "404140",
      "title": "Kids Lic Crew Jolly Ranch Pink",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/404140.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-404146",
      "sku": "404146",
      "title": "Kids Lic Crew Hershey Bar 2",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/404146.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    },
    {
      "id": "catalog-404148",
      "sku": "404148",
      "title": "Kids Lic Crew Reeses Pieces",
      "retailer": "Dollar Tree",
      "price": "$0.01",
      "was": "$1.25",
      "off": "99%",
      "freshness": "watchlist",
      "comments": 0,
      "velocity": 0,
      "image": "images/404148.jpg",
      "dealType": "penny-watch",
      "worthScore": 7.5,
      "note": "Catalog penny watchlist item with a local reference photo for in-store family review."
    }
  ]
};
window.STAGING_DEALS = window.STAGING_SNAPSHOT.deals;
